### ISSUE TITLE
ImportError: cannot import name 'weak_module'

### ISSUE THREAD

**Issue by weixia1** [Media-Smart/vedaseg#14]
I get the error:

> ImportError: cannot import name 'weak_module'

when I running the following command `python tools/trainval.py configs/deeplabv3plus.py` and my PyTorch version is `1.3.0`
### Reason
After reading the source code from PyTorch, I found `weak_script_method` is in `_jit_internal.py` in version` v1.1.0`. 
But, after version `v1.2.0` PyTorch has removed the function [detail](https://github.com/pytorch/pytorch/commit/10c4b98ade8349d841518d22f19a653a939e260c#diff-ee07db084d958260fd24b4b02d4f078d)

**Comment by DarthThomas** [comment]
Hi!

We have spotted the problem and will update within a few days, you can try [this pull request](https://github.com/Media-Smart/vedaseg/pull/13) to see if it solves your problem

**Comment by hxcai** [comment]
@weixia1 we have fixed this problem and you can download the newest code.

**Comment by weixia1** [comment]
@DarthThomas @hxcai thank you

**Comment by Nikki-kumari** [comment]
How to solve this issue?
