### ISSUE TITLE
Implementation Error of ResNet BasicBlock

### ISSUE THREAD

**Issue by xpngzhng** [Media-Smart/vedaseg#20]
Hi, I was trying to train with a resnet34 backbone, and find mismatch when loading pretrained model
I find some error 

left, the implementation of this repo, is wrong, right is correct
![image](https://user-images.githubusercontent.com/14209404/77622672-a51ba600-6f79-11ea-9c6e-8353525db175.png)

**Comment by hxcai** [comment]
@xpngzhng thanks for your advice! we have fixed this bug and you can pull the newest code.
