### ISSUE TITLE
Any support for Resnet50 backbone?

### ISSUE THREAD

**Issue by YAOYI626** [Media-Smart/vedaseg#25]
Will it work if I modify the config file like following ?
```
        backbone=dict(
            type='ResNet',
            arch='resnet50',
        ),
```

**Comment by mileistone** [comment]
yes, you can refer to [resnet](https://github.com/Media-Smart/vedaseg/blob/master/vedaseg/models/encoders/backbones/resnet.py) for details.

**Comment by YAOYI626** [comment]
thanks @mileistone timely reply! I'll close the issue.
