### ISSUE TITLE
Support more datasets

### ISSUE THREAD

**Issue by Spritea** [Media-Smart/vedaseg#3]
Nice job! 

- I was wondering whether you would support more datasets, like Cityscape and COCO, since these models are also used widely in related papers. 

- Besides, would you continue to maintain this repo, just like MMDetection, so we can use it without worrying that it would be abandoned suddenly?
  
Thanks!

**Comment by hxcai** [comment]
@Spritea Hi~
1、We will support more datasets and pretrained models soon.
2、We will continue to maintain this repo. And welcome to contribute to our repo if you have re-implemented some new fancy frameworks.
