### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by jonguo111** [Media-Smart/vedaseg#35]
Thank you for your work. I followed the installation instructions and encountered the following error. Do you have any ideas on this? 
![image](https://user-images.githubusercontent.com/43916561/93019843-95376300-f5a7-11ea-9932-0d745ec5525d.png)

**Comment by Rajrup** [comment]
I guess you have similar issue. 
#33 this solved the issue.

**Comment by YuxinZou** [comment]
Hi @Rajrup @jonguo111 ,
we update a new version, which add default samplers for both distributed and non-distributed training without any modification in config file.
