### ISSUE TITLE
About accuracy

### ISSUE THREAD

**Issue by Spritea** [Media-Smart/vedaseg#4]
Hello~
It seems that there is still a gap between the current mIoU and the ones reported in papers. Would you consider to improve the mIoU? Thanks.

**Comment by hxcai** [comment]
@Spritea Hi~
We think the performance of the deeplab models is similar to the ones reported in papers. As for pspnet, we do not use the auxiliary loss and special test time augmentation in original code.

**Comment by Spritea** [comment]
Thanks for your reply!
I checked the paper again, and you are right. 

- The paper result of DeepLab v3 is **77.21% mIoU**, and the setting is: train OS=16, eval OS=16, without MS and Flip.

- The paper result of DeepLab v3+ is **78.85% mIoU**, and the setting is : train OS=16, eval OS=16, without MS and Flip.

And does the OS on the table of ReadMe file only represent the eval OS for all models? I guess the train OS is set as 16 for all models. Thanks!

**Comment by hxcai** [comment]
@Spritea We train all models following corresponding papers. For example, we train deeplab models with output stride 16, and we train pspnet model with output stride 8. The training details are all in our config files.
