### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by wangshaonian666** [Media-Smart/vedaseg#52]
Hello, I want to apply this program on Windows platform.Do you have any installation tutorials on Windows，thank you！

**Comment by DarthThomas** [comment]
hi @wangshaonian666, thanks for your interest in our Vedaseg! Currently, we don't have windows machines here so we are unable to develop and test our tools on windows. But you can still try it yourself:
    1. working on building environment first, anaconda currently support windows
    2. try to install and see if there is any problem
