### ISSUE TITLE
The prepare data operation is a little complicated

### ISSUE THREAD

**Issue by GeneralLi95** [Media-Smart/vedaseg#6]
Is there any way to simplify this procedure or could you please give the file structure after the operation.

**Comment by GeneralLi95** [comment]
I figure out finally while `argument list too long: cp` occurs when we do the first copy operation. I copy it manully.

**Comment by mileistone** [comment]
we fix the "argument list too long: cp" problem, and you can have a look at the readme again. To simplify the procedure, you can save the linux commands as a shell file and excute it.

**Comment by GeneralLi95** [comment]
@mileistone  Thank you. I have noticed that and it works now.
