### ISSUE TITLE
backbone checkpoints

### ISSUE THREAD

**Issue by GeneralLi95** [Media-Smart/vedaseg#7]
Thank you for your great job. Can you share the link to download the backbone checkpoints.

**Comment by hxcai** [comment]
@GeneralLi95 https://github.com/pytorch/vision/tree/master/torchvision/models

**Comment by mileistone** [comment]
It will download the backbone checkpoints automatically, you don't have to pay attention to this.

**Comment by GeneralLi95** [comment]
@mileistone Thank you. Maybe my net connection is strong. The automatic download failed. So I decided to download it manually then put it to the place.
